### ISSUE TITLE
Panic from STDIN with -o

### ISSUE THREAD

**Issue by hymkor** [zetamatta/pipe2excel#1]
```
$ type 13keta.csv
123456789012345,A,B,C
$ pipe2excel.exe -o 13keta.xlsx < 13keta.csv
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xe24960]

goroutine 1 [running]:
github.com/tealeg/xlsx.(*Sheet).AddRow(...)
        C:/Users/zetamatta/go/pkg/mod/github.com/tealeg/xlsx@v1.0.5/sheet.go:52
main.(*SendCsvToXlsx).Send(0xc00001e580, 0xc0000402c0, 0x4, 0x4, 0x0, 0x0)
        C:/Users/zetamatta/goes/pipe2excel/toxlsx.go:32 +0x80
main.parseCsvReader(0xeab5a8, 0xc000040280, 0xeacf78, 0xc00001e580, 0xc000040280, 0x2e)
        C:/Users/zetamatta/goes/pipe2excel/main.go:51 +0x1c4
main.parseCsvFile(0xe6eda6, 0x1, 0xeacf78, 0xc00001e580, 0x0, 0x0)
        C:/Users/zetamatta/goes/pipe2excel/main.go:59 +0x234
main.main1(0xc00007fec8, 0x1, 0x1, 0x0, 0x0)
        C:/Users/zetamatta/goes/pipe2excel/main.go:98 +0x2cf
main.main()
        C:/Users/zetamatta/goes/pipe2excel/main.go:116 +0xc5
exit status 2
$ pipe2excel.exe -o 13keta.xlsx 13keta.csv
(no panics)
```

**Comment by hymkor** [comment]
Fixed !
